In [2]:
import numpy as np

Индексация массивов в NumPy

In [4]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1]

np.int64(1)

In [6]:
arr[1: 5]

array([1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

**Операция Broadcast**

In [8]:
arr[5:10] = 999
arr

array([  0,   1,   2,   3,   4, 999, 999, 999, 999, 999,  10])

Срез array является ссылкой

In [13]:
arr = np.arange(0, 11)
slice = arr[1:5]
arr[2] = 9999
slice

array([   1, 9999,    3,    4])

In [14]:
slice[:] = 900
arr

array([  0, 900, 900, 900, 900,   5,   6,   7,   8,   9,  10])

**Копия array**


In [16]:
arr_1 = np.copy(arr)
arr[:] = 103
arr_1

array([  0, 900, 900, 900, 900,   5,   6,   7,   8,   9,  10])

**Срез по матрице**

In [19]:
arr = np.array([[1, 2, 3], [3, 4, 5], [10, 11, 12]])
arr[:2, 1:]

array([[2, 3],
       [4, 5]])

**Выбор по условию**

In [20]:
arr = np.arange(1, 20)
arr % 2 ==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [24]:
bool_array = arr > 4
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
arr = np.array([[1, 2, 3], [3, 4, 5], [10, 11, 12]])
arr[arr > 4]

array([ 5, 10, 11, 12])