In [1]:
import numpy as np

Операции в NumPy

In [2]:
arr = np.arange(0, 10)
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
arr - 5


array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [4]:
arr * 5


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
arr = np.arange(0, 10)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr / arr # обратить внимание на результат деления на 0


/tmp/ipykernel_185278/46910809.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr # обратить внимание на результат деления на 0


/tmp/ipykernel_185278/809036706.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr = np.arange(1, 10)

np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

**Так же присутствует и множество других функций**

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr.max()

np.int64(9)

In [19]:
arr.min()

np.int64(1)

In [20]:
arr.sum()

np.int64(45)

In [22]:
arr.mean() # среднее значение

np.float64(5.0)

In [23]:
arr.var() #дисперсия


np.float64(6.666666666666667)

In [24]:
arr.std() # средне квадратичное отклонение

np.float64(2.581988897471611)

In [25]:
arr.T #транспонирование вектора/матрицы


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
matr = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
matr

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [29]:
matr.T

array([[1, 3, 4],
       [2, 4, 5],
       [3, 5, 6]])

In [31]:
vector_not_unique = np.array([1, 2, 3, 4, 5, 6, 5, 4, 6, 10])
np.unique(vector_not_unique) # уникальность элементов(удаляет повторяющиеся)

array([ 1,  2,  3,  4,  5,  6, 10])

Работа со строками/столбцами в n-мерном пространстве

In [32]:
arr = np.arange(0, 25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
np.sum(arr, axis = 0 ) # сумма по колонкам

array([50, 55, 60, 65, 70])

In [35]:
np.sum(arr, axis = 1 ) # суммы в отдельных строках

array([ 10,  35,  60,  85, 110])