In [42]:
import numpy as np

Шпаргалка по NumPy

In [43]:
import numpy as np
num_1 = np.array([1, 2, 3])
np.arange(3, 0, -1)

array([3, 2, 1])

Нулевая матрица:

In [44]:
np.zeros((3, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros(3)

array([0., 0., 0.])

**Единичные вектора**---

In [46]:
np.ones((3, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones(3 , dtype=float)

array([1., 1., 1.])

**n Чисел в диапазоне с равной разницей:**

In [48]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [49]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Единичная матрица

In [50]:
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Псевдослучайные вектора в интервале [0, 1)


In [51]:
np.random.rand(3, 5)

array([[-0.57138017, -0.92408284, -2.61254901,  0.95036968,  0.81644508],
       [-1.523876  , -0.42804606, -0.74240684, -0.7033438 , -2.13962066],
       [-0.62947496,  0.59772047,  2.55948803,  0.39423302,  0.12221917]])

Случайные целый в интервале

In [52]:
np.random.randint(2, 300, (2, 2))

array([[ 22, 168],
       [275,  90]])

Случайные по сид-числу

In [84]:
np.random.seed(22)
np.random.rand(3, 5)

array([[0.20846054, 0.48168106, 0.42053804, 0.859182  , 0.17116155],
       [0.33886396, 0.27053283, 0.69104135, 0.22040452, 0.81195092],
       [0.01052687, 0.5612037 , 0.81372619, 0.7451003 , 0.18911136]])

Метод для форматирования размерности

In [64]:
arr = np.arange(0, 25)
# эквивалентные записи
print(np.reshape(arr, (5, 5)))
arr.reshape(5, 5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max min armax argmin

In [65]:
arr = np.arange(0, 125)
arr.max()

np.int64(124)

In [66]:
arr.min()

np.int64(0)

In [67]:
arr.argmin()

np.int64(0)

Атрибуты NumPy:

In [68]:
arr.dtype

dtype('int64')

In [69]:
arr.shape

(125,)

In [93]:
arr = np.arange(0, 25)
arr = arr.reshape(5, 5)
arr.shape

(5, 5)